project_id = "spwlnjuqephrodvymixr"

[functions.submit-review]
verify_jwt = false

[functions.fetch-book-data]
verify_jwt = false

[functions.enrich-books]
verify_jwt = false

[functions.get-recommendations]
verify_jwt = false

[functions.get-similar-books]
verify_jwt = false

[functions.import-csv-books]
verify_jwt = false

[functions.handle-lemon-squeezy-webhook]
verify_jwt = false
