project_id = "spwlnjuqephrodvymixr"

[functions.submit-review]
verify_jwt = true

[functions.fetch-book-data]
verify_jwt = false

[functions.enrich-books]
verify_jwt = true

[functions.enrich-single-book]
verify_jwt = true

[functions.batch-enrich-books]
verify_jwt = true

[functions.get-recommendations]
verify_jwt = false

[functions.get-similar-books]
verify_jwt = false

[functions.import-csv-books]
verify_jwt = true

[functions.handle-lemon-squeezy-webhook]
verify_jwt = false

[functions.create-lemon-squeezy-checkout]
verify_jwt = true

[functions.recategorize-book-moods]
verify_jwt = true

[functions.recategorize-book-tropes]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true
